### ISSUE TITLE
GetListValue not working with checkbox values

### ISSUE THREAD

**Issue by justincolangelo** [dirigodev/DirigoEdgeCore#39]
Create a schema with a list of fields with at least one field being a checkbox.
Create a shortcode that uses a module with that schema.
Calling `yourModule.GetListValue("fieldName")` fails to parse.

**Comment by frxnz** [comment]
The problem is that checkbox fields return an array. `GetCheckboxValue` returns `List<string>` where `GetListValue` returns `List<Dictionary<string, string>>`. We would need it to return `List<Dictionary<string, List<string>>>` for checkbox fields.

**Comment by Feasoron** [comment]
This is an issue with old schemas, not 3.0
